disabled_rules:
  - identifier_name
  - trailing_whitespace
  - discouraged_direct_init

opt_in_rules:
  - attributes
  - class_delegate_protocol
  - closure_parameter_position
  - closure_spacing
  - computed_accessors_order
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_cast
  - force_try
  - implicit_getter
  - implicit_return
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - todo
  - unused_closure_parameter
  - valid_ibinspectable
  - vertical_parameter_alignment_on_call
  - weak_delegate

included:
  - Repair-Motorbike-iOS

excluded:
  - Carthage
  - Pods
  - Repair-Motorbike-iOS/*/Logger.swift

line_length: 250
file_length: 500
function_parameter_count: 10
cyclomatic_complexity: 100

type_body_length:
  - 520 # warning
  - 550 # error

function_body_length:
  - 300 # warning
  - 300 # error

type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 45
    error: 45

large_tuple:
  - 3 # warning
  - 4 # error

nesting:
  type_level: 3
